//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonentEquipment
    {
        public int AbonEquipID { get; set; }
        public string AbonentID { get; set; }
        public string EquipID { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
