//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class admin
    {
        public string GetPhoto
        {
            get
            {
                if (photo_admin is null)
                { return Directory.GetCurrentDirectory() + @"\Images\Лого ТНС.jpg"; }
                return Directory.GetCurrentDirectory() + @"\Images\" + photo_admin.Trim();
            }
        }
        public string GetRole
        {
            get
            {
                if (id_dolgj == 1)
                {
                    return "Руководитель по работе с клиентами";
                }
                else if (id_dolgj == 2)
                {
                    return "Руководитель отдела технической поддержки";
                }
                else if (id_dolgj== 3)
                {
                    return "Специалист ТП (выездной инженер)";
                }
                else if (id_dolgj == 4)
                {
                    return "Директор по развитию";
                }
                else if (id_dolgj == 5)
                {
                    return "Технический департамент";
                }
                else if (id_dolgj == 6)
                {
                    return "Бухгалтер";
                }
                else if (id_dolgj == 7)
                {
                    return "Менеджер по работе с клиентами";
                }
                else
                {
                    return "пользователь";
                }
            }
        }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronimyc { get; set; }
        public int id_dolgj { get; set; }
        public string id_admin { get; set; }
        public string photo_admin { get; set; }
    
        public virtual dolgjnost dolgjnost { get; set; }
    }
}
