//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class adress_client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adress_client()
        {
            this.client = new HashSet<client>();
        }
    
        public int id_strana { get; set; }
        public int id_gorod { get; set; }
        public int id_ulicta { get; set; }
        public string number_house { get; set; }
        public string number_kvartira { get; set; }
        public int id_adress_client { get; set; }
    
        public virtual gorod gorod { get; set; }
        public virtual strana strana { get; set; }
        public virtual ulitca ulitca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> client { get; set; }
    }
}
