//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public string ApplicNumb { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public string AbonentID { get; set; }
        public int ServiceID { get; set; }
        public int ServViewID { get; set; }
        public int ServTypeID { get; set; }
        public int StatusID { get; set; }
        public string Opisanie { get; set; }
        public Nullable<System.DateTime> DateOfRealiz { get; set; }
        public int ProblemID { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual Service Service { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual ServiceView ServiceView { get; set; }
        public virtual Status Status { get; set; }
    }
}
