//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_admin
    {
        public int id_info { get; set; }
        public int id_dolgj { get; set; }
        public string info { get; set; }
    
        public virtual dolgjnost dolgjnost { get; set; }
    }
}
