//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchebkaEntities : DbContext
    {
        public uchebkaEntities()
            : base("name=uchebkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<adress_client> adress_client { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<client_oborud> client_oborud { get; set; }
        public virtual DbSet<contract_type> contract_type { get; set; }
        public virtual DbSet<dolgjnost> dolgjnost { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<gorod> gorod { get; set; }
        public virtual DbSet<info_admin> info_admin { get; set; }
        public virtual DbSet<magistral> magistral { get; set; }
        public virtual DbSet<rayoun> rayoun { get; set; }
        public virtual DbSet<seti_dostupa> seti_dostupa { get; set; }
        public virtual DbSet<seti_name> seti_name { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<strana> strana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_problem> type_problem { get; set; }
        public virtual DbSet<type_uslugi> type_uslugi { get; set; }
        public virtual DbSet<type_zastroyki> type_zastroyki { get; set; }
        public virtual DbSet<ulitca> ulitca { get; set; }
        public virtual DbSet<uslugaCRM> uslugaCRM { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
        public virtual DbSet<vid_uslugi> vid_uslugi { get; set; }
        public virtual DbSet<zayavka_CRM> zayavka_CRM { get; set; }
    }
}
