//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class rayoun
    {
        public int id_rayoun { get; set; }
        public string name { get; set; }
        public double plosdad { get; set; }
        public int naselenie { get; set; }
        public int kolvo_stancii { get; set; }
        public int id_type_zastroiki { get; set; }
    
        public virtual type_zastroyki type_zastroyki { get; set; }
    }
}
