//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.DataTable
{
    using System;
    using System.Collections.Generic;
    
    public partial class zayavka_CRM
    {
        public string id_CRM { get; set; }
        public int id_uslugaCRM { get; set; }
        public int id_vid_uslugi { get; set; }
        public int id_type_uslugi { get; set; }
        public int id_status { get; set; }
        public string type_oborud { get; set; }
        public string opisanie_problem { get; set; }
        public Nullable<System.DateTime> date_zakritie { get; set; }
        public int id_type_problem { get; set; }
    
        public virtual status status { get; set; }
        public virtual type_problem type_problem { get; set; }
        public virtual type_uslugi type_uslugi { get; set; }
        public virtual uslugaCRM uslugaCRM { get; set; }
        public virtual vid_uslugi vid_uslugi { get; set; }
    }
}
